# Postgres docker-compose.yml file from docker hub examples

services:
  java-daily-expenses:
    image: java-daily-expenses:11
    container_name: java-daily-expenses
    ports:
      - "8089:8089"
    environment:
      DB_SERVER_HOST: postgres
      DB_SERVER_PORT: 5432
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M
  db:
    image: postgres
    container_name: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=daily-expenses-db
  kafka:
    image: apache/kafka:4.3.1
    container_name: kafka-java-daily-expenses
    restart: always
    ports:
      - 9092:9092
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - /home/caio-caminha/Documents/projects/java-daily-expenses-management/grafana/grafana-volume:/var/lib/grafana
  prometheus:
    image: prom/prometheus
    container_name: prometheus-java-daily-expenses
    restart: always
    ports:
      - 9090:9090
    volumes:
      - /home/caio-caminha/Documents/projects/java-daily-expenses-management/prometheus-testing/prometheus.yml:/etc/prometheus/prometheus.yml
