server.port=8089
spring.application.name=expenses-manager


#OBSERVABILITY PROPERTIES
# Expose all actuator endpoints
management.endpoints.web.exposure.include=*
management.endpoint.metrics.enabled=true
management.endpoint.health.show-details=always

# Enable Prometheus metrics
management.prometheus.metrics.export.enabled=true

# JVM metrics (memory, GC, CPU)
management.metrics.enable.jvm=true
management.metrics.enable.process=true
management.metrics.enable.system=true

#CUSTOM R2DBC CONFIGURATION
db.name = daily-expenses-db
db.user = postgres
db.password = postgres
db.url = r2dbc:postgresql://${db.server.host}:${db.server.port}/${db.name}
db.server.port= ${DB_SERVER_PORT:5432}
db.server.host=${DB_SERVER_HOST:127.0.0.1}

#JDBC LIQUIBASE ONLY
spring.datasource.url = ${db.url}
spring.datasource.username = ${db.user}
spring.datasource.password = ${db.password}

#/home/caio-caminha/Documents/projects/java-daily-expenses-management/src/main/resources/db/changelog/changelog.yaml
spring.liquibase.change-log=classpath:/db/changelog/changelog.yaml
spring.liquibase.url=jdbc:postgresql://${db.server.host}:${db.server.port}/${db.name}
spring.liquibase.user=${db.user}
spring.liquibase.password=${db.password}

spring.threads.virtual.enabled=true
#To ensure that JVM is kept alive even though all running threads are virtual threads
#Virtual threads are created as deamon threads, and the JVM will exit if all threads are deamon threads
spring.main.keep-alive=true

client.openai.baseUrl=https://api.openai.com/v1

#Should be enabled on prod in order to prevent condition evaluation report to being logged | Keep logs clean
#It's a report of changes to the application's auto-configuration as beans are added or removed and setting configurations
#spring.devtools.restart.log-condition-evaluation-delta=false
logging.level.root=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR

#REDIS PROPERTIES


